### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' due to null value _lodash2.default.forEach

### ISSUE THREAD

**Issue by KyooMario** [multinerd/formio-export#2] opened 2019-06-13 08:33 UTC
Hello Multinerd,

When we try to get the solution working we stumble across the following error: Uncaught TypeError: Cannot read property 'forEach' due to null value _lodash2.default.forEach

Can you advise how to fix this?

Kind regards,
Mario

**Comment by multinerd** [comment] 2019-06-13 14:37
Can you share your code (or a snippet) reproducing the problem.

**Comment by KyooMario** [comment] 2019-06-13 14:47
Hello Multinerd,

Thanks. Attached my Html. I used your code.
[FormioExport-Html.txt](https://github.com/multinerd/formio-export/files/3286730/FormioExport-Html.txt)

Kind regards,
Mario

**Comment by KyooMario** [comment] 2019-06-13 14:54
Here the error message in the console.

![FormioExport-Error](https://user-images.githubusercontent.com/38975838/59443218-db79a180-8dfb-11e9-909c-be9747bc9886.png)

**Comment by multinerd** [comment] 2019-06-13 17:07
You need to include `formio.js`

```html

<!-- put these in <head></head> -->
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://unpkg.com/formiojs@latest/dist/formio.full.min.css'>

<!-- this must come BEFORE formioexport.js -->
<script src='https://unpkg.com/formiojs@latest/dist/formio.full.min.js'></script> 
<script src="formio-export.min.js"></script>
```

**Comment by KyooMario** [comment] 2019-06-13 18:32
Hello Multinerd,

Great that covered the error message No. 1.
The other one is: Uncaught ReferenceError: FormioExport is not defined

Any advise on that?

Kind regards,
Mario

**Comment by multinerd** [comment] 2019-06-13 18:38
Hmm, i was not able to reproduce that error with the code you provided.

**Comment by multinerd** [comment] 2019-06-13 18:41
Can you give this a try.
 
[Compressed file.zip](https://github.com/multinerd/formio-export/files/3287626/Compressed.file.zip)

**Comment by KyooMario** [comment] 2019-06-13 18:50
Hello Multinerd,

Great. This solved it and I got the pdf download. Thanks a lot.
Did you update the code source also?

Kind regards,
Mario

**Comment by multinerd** [comment] 2019-06-13 18:57
The files i provided was from a clean build from my source. I could be wrong but i believe you were using the compiled version from https://github.com/fast-platform/fast-export (i was not able to get this to work, hence my fork)

I updated the repo to include the `lib` folder (compiled) + `demo.html`

**Comment by KyooMario** [comment] 2019-06-13 19:04
OK. I did not do a build. I supposed the builds were in the source. My bad.

Thanks for the help and for the quick response. Is appreciated.

Just for your information: I am integrating formio in the Salesforce platform and possibly later in Sharepoint. If you would like to know more about this then just let me know. OK?

Kind regards,
Mario

**Comment by multinerd** [comment] 2019-06-13 19:08
Glad I can help. I'll be closing this issue now. 

Feel free to open another issue if you have one, but you should know I do not plan on adding new features. You can try your luck with the original developer, though he seems to be MIA.

Original Dev: https://github.com/fast-platform/fast-export

**Closed as completed by multinerd** 2019-06-13 19:08 UTC
